CREATE TABLE `comparables` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`category` enum('SOLD_6MO','SOLD_12MO','PENDING','FOR_SALE','FOR_RENT') NOT NULL,
	`address` varchar(500) NOT NULL,
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`squareFeet` int,
	`lotSize` varchar(100),
	`yearBuilt` int,
	`distanceFromSubject` varchar(50),
	`saleDate` varchar(50),
	`listedDate` varchar(50),
	`amount` int,
	`buyerName` varchar(255),
	`overallCondition` varchar(100),
	`source` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `comparables_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `renovationEstimates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`squareFeet` int NOT NULL,
	`numberOfBathrooms` int DEFAULT 1,
	`estimatedPropertyValue` int,
	`kitchenCost` int,
	`bathroomCost` int,
	`paintingCost` int,
	`flooringCost` int,
	`roofCost` int,
	`acCost` int,
	`cleaningCost` int,
	`gardensCost` int,
	`renovationSubtotal` int,
	`miscellaneous` int,
	`permitsAndRelated` int,
	`holdCost` int,
	`realEstateCommission` int,
	`totalGeral` int,
	`offer60` int,
	`offer70` int,
	`offer90` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `renovationEstimates_id` PRIMARY KEY(`id`),
	CONSTRAINT `renovationEstimates_propertyId_unique` UNIQUE(`propertyId`)
);
