CREATE TABLE `deepSearchOverview` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`ds_propertyType` enum('Single Family Home','Condo','Duplex','Triplex','Fourplex','Townhouse','Mobile Home','Vacant Lot','Other'),
	`ds_propertyUse` enum('Residential','Commercial','Mixed Use'),
	`ds_propertyTags` text,
	`ds_conditionRating` enum('Excellent','Good','Fair','Average','Poor'),
	`ds_conditionTags` text,
	`ds_occupancy` enum('Vacant','Owner Occupied','Tenant Occupied','Squatter Occupied','Unknown'),
	`ds_evictionRisk` enum('Low','Medium','High'),
	`ds_evictionNotes` text,
	`ds_sellerFinancialPressure` text,
	`ds_sellerLifeEvents` text,
	`ds_sellerLegalBehavioral` text,
	`ds_legalOwnershipTitle` text,
	`ds_legalCourtLawsuit` text,
	`ds_legalPropertyStatus` text,
	`ds_probate` int DEFAULT 0,
	`ds_probateStage` enum('Not Started','Open Case','Executor Assigned','Court Approval Required','Ready to Sell','Probate Not Completed','Finished'),
	`ds_probateFindings` text,
	`ds_generalNotes` text,
	`ds_probateNotes` text,
	`ds_internalNotes` text,
	`ds_distressScore` int DEFAULT 0,
	`ds_distressDrivers` text,
	`ds_createdAt` timestamp NOT NULL DEFAULT (now()),
	`ds_updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deepSearchOverview_id` PRIMARY KEY(`id`),
	CONSTRAINT `deepSearchOverview_propertyId_unique` UNIQUE(`propertyId`)
);
--> statement-breakpoint
CREATE TABLE `financialModule` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`fm_delinquentTax2025` int,
	`fm_delinquentTax2024` int,
	`fm_delinquentTax2023` int,
	`fm_delinquentTax2022` int,
	`fm_delinquentTax2021` int,
	`fm_delinquentTax2020` int,
	`fm_delinquentTaxTotal` int,
	`fm_taxNotes` text,
	`fm_needsRepairs` int DEFAULT 0,
	`fm_repairCategories` text,
	`fm_estimatedRepairCost` int,
	`fm_repairNotes` text,
	`fm_mortgage` enum('Yes','No','Unknown'),
	`fm_mortgageNotes` text,
	`fm_liens` int DEFAULT 0,
	`fm_totalLienAmount` int,
	`fm_lienTypes` text,
	`fm_lienNotes` text,
	`fm_preForeclosure` int DEFAULT 0,
	`fm_auctionScheduled` int DEFAULT 0,
	`fm_lisPendens` int DEFAULT 0,
	`fm_nodFiled` int DEFAULT 0,
	`fm_foreclosureNotes` text,
	`fm_codeViolations` int DEFAULT 0,
	`fm_taxLien` int DEFAULT 0,
	`fm_codeTaxNotes` text,
	`fm_deedHistory` text,
	`fm_createdAt` timestamp NOT NULL DEFAULT (now()),
	`fm_updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financialModule_id` PRIMARY KEY(`id`),
	CONSTRAINT `financialModule_propertyId_unique` UNIQUE(`propertyId`)
);
